# Generated by Django 6.0.5 on 2026-05-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choices',
            new_name='choices_text',
        ),
    ]
